name: Bundle
on:
  push:
    branches:
      - 'main'
      - 'v*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
      - 'v*'
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: test deno ${{ matrix.deno }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        deno: [v1.8]
      fail-fast: true
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: ${{ matrix.deno }}
      - name: Check formatting
        if: matrix.os == 'ubuntu-latest'
        run: deno fmt --check -c deno.json
#      - name: Check linting
#        if: matrix.os == 'ubuntu-latest'
#        run: deno lint -c deno.json
      - name: Run tests unstable
        run: deno test --unstable --allow-net --allow-env --allow-run --allow-read --allow-write --coverage=cov test/
      - name: Generate lcov
        if: |
          matrix.os == 'ubuntu-latest' &&
          matrix.deno == 'v1.x'
        run: deno coverage --lcov cov > cov.lcov
      - name: Upload coverage
        if: |
          matrix.os == 'ubuntu-latest' &&
          matrix.deno == 'v1.x'
        uses: codecov/codecov-action@v1
        with:
          files: cov.lcov
      - name: Release info
        if: |
          github.repository == 'letheanVPN/lethean-server' &&
          matrix.os == 'ubuntu-latest' &&
          matrix.deno == 'v1.x' &&
          startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Bundle
        if: env.RELEASE_VERSION != ''
        run: |
          mkdir -p target/release
          deno bundle mod.ts target/release/lethean-server_${RELEASE_VERSION}.js
      - name: Release
        uses: softprops/action-gh-release@v1
        if: env.RELEASE_VERSION != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            target/release/lethean-server_${{ env.RELEASE_VERSION }}.js
